name: Test Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  self-hosted-job:
    runs-on: [self-hosted]
    name: Subash Runner Job
    steps:
      - name: Allow PowerShell script execution
        shell: powershell
        run: Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force

      - name: Confirm runner is working
        run: |
          echo "Hello from Subash's self-hosted runner!"
          echo "Running as: $USER"
          hostname
          date
