name: Test Self-Hosted Runner

on:
  workflow_dispatch:
 
jobs:
  self-hosted-job:
    runs-on: [self-hosted]
    name: Subash Runner Job
    steps:
      - name: Confirm runner is working on Windows with policy update
        shell: powershell
        run: |
          try {
            Set-ExecutionPolicy -Scope Process -ExecutionPolicy RemoteSigned -Force -ErrorAction Stop
            Write-Host "Execution policy set successfully."
          } catch {
            Write-Host "Failed to set execution policy. Error: $_"
          }
          Write-Host "Hello from Subash's self-hosted runner!"
          Write-Host "Running as: $env:USERNAME"
          hostname
          Get-Date
